name: "Markdown VSCode Contributions Action"
description: "Generate markdown tables from vscode contributions"
author: "Jeronimo Ekerdt"

runs:
  using: "node16"
  main: "src/index.js"

branding:
  icon: "book-open"
  color: "blue"

inputs:
  github-token:
    description: "Github token"
    default: ${{ github.token }}
    required: false

  git-message:
    description: "Commit message to use"
    default: "updated Markdown with VSCode contributions"
    required: false

  git-user-name:
    description: "The git user.name to use for the commit"
    default: "Markdown VSCode Contributions Action"
    required: false

  git-user-email:
    description: "The git user.email to use for the commit"
    default: "markdown.vscode.contributions.action@github.com"
    required: false

  git-pull-method:
    description: "The git pull method used when pulling all changes from remote"
    default: "--ff-only"
    required: false

  git-push:
    description: "Should all git changes be pushed"
    default: "true"
    required: false

  git-branch:
    description: "The git branch to be pushed"
    default: ${{ github.ref }}
    required: false

  git-url:
    description: "Git Url"
    default: "github.com"
    required: false

  git-path:
    description: "Path filter for the logs. If set, only commits that match the path filter will be considered"
    default: ""
    required: false

  input-path:
    description: "Input markdown file path"
    default: "README.md"
    required: false

  output-path:
    description: "Output markdown file path. By default it takes the input-path value"
    required: false

  package-path:
    description: "The path to the package.json file that contains the VSCode contributions"
    default: "package.json"
    required: false

  skip-git-pull:
    description: "Do not pull the repo before tagging. Ensure you full cloned the repo in the first place to get tags"
    default: "false"
    required: false

  skip-on-no-changes:
    description: "Do nothing when the markdown hasn't changed"
    default: "true"
    required: false

  skip-commit:
    description: "Do create a release commit"
    default: "false"
    required: false

  skip-ci:
    description: "Adds [skip ci] to commit message"
    default: "true"
    required: false

outputs:
  markdown_output:
    description: "The readme output"
  markdown_changed:
    description: "boolean if the readme output changed"
  skipped:
    description: "boolean to check if this step have been skipped"
